server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
        http-only: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/super_partner?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 2
  jackson:
    time-zone: GMT+8
    date-format: java.text.SimpleDateFormat
  # todo 邮箱配置
  mail:
    host: host
    username: username
    password: password
  session:
    store-type: redis
    # 5小时过期
    timeout: 18000
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: on
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: isDelete
      id-type: auto
knife4j:
  enable: true
  openapi:
    title: Shier伙伴匹配接口文档
    description: "用户匹配系统"
    email: 2927527234@qq.com
    version: v2.0.0
    concat: Shier
    group:
      super:
        group-name: shier
        api-rule: package
        api-rule-resources:
          - com.shier
campus:
  img: /img/
  job: "0 0 0 * * ? *"
# 阿里云对象存储  todo 需替换配置
aliyun:
  oss:
    file:
      endpoint: oss-cn-guangzhou.aliyuncs.com
      keyid: xxxx
      keysecret: xxxxx
      bucketname: xxxxx